--------------------------------------------------------
--  파일이 생성됨 - 월요일-11월-06-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USER_INFO
--------------------------------------------------------

  CREATE TABLE "SHINEE"."USER_INFO" 
   (	"USER_ID" VARCHAR2(12 BYTE), 
	"USER_NAME" VARCHAR2(15 BYTE), 
	"USER_NICKNAME" VARCHAR2(20 BYTE), 
	"USER_PASSWORD" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PHONE_NUMBER" VARCHAR2(11 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "SHINEE"."PK_ID" ON "SHINEE"."USER_INFO" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USER_INFO
--------------------------------------------------------

  ALTER TABLE "SHINEE"."USER_INFO" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SHINEE"."USER_INFO" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SHINEE"."USER_INFO" MODIFY ("USER_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SHINEE"."USER_INFO" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SHINEE"."USER_INFO" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SHINEE"."USER_INFO" ADD CONSTRAINT "PK_ID" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
